base: 'https://live-startsmart.made-by-comkom.de/'
baseVariants:
  -
    base: dev-startsmart.made-by-comkom.local
    condition: 'applicationContext == "Development"'
  -
    base: 'https://stage-startsmart.made-by-comkom.de'
    condition: 'applicationContext == "Production/Staging"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de-DE
    direction: ltr
    flag: de
    websiteTitle: ''
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: EN
    hreflang: en-US
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: .html
    map:
      .html: 0
      sitemap.xml: 1533906435
websiteTitle: 'COMKOMÂ° DIGITAL MEDIA'
